### ISSUE TITLE
Show name in addition to nip05 identifier

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#10]
Setting a nip05 identifier makes the name go disappear. I'd really prefer to be referenced by my name, not my id.

**Comment by monlovesmango** [comment]
from my understanding NIP05 is supposed to be a way to assign unique usernames in a decentralized way. for now I am going to leave it as is, bc I think this is the most important identifier for users to see and don't want to clutter the post.

I do think the user should be able to choose whether they see name or the NIP05 identifier displayed (or both). I do not think I should be able choose how another user sees my name/NIP05 displayed.

if you still feel strongly about this, feel free to leave it open until user personalizations are available.

**Comment by Giszmo** [comment]
I agree with your sentiment. Just right now I can't see users names if they also have set an id.

**Comment by Semisol** [comment]
I would suggest a twitter like approach, with a NIP-05 at the bottom, and the name at the top.

**Comment by monlovesmango** [comment]
name and nip05 id are now both displayed
