### ISSUE TITLE
Auto-mirror events

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#100]
I love that Astral lets me see on which relay a message was found and even to send to missing relays but this could be automated a bit.

Please provide an option for auto-mirroring that lets me mirror all events I interact with to all my relays that don't have it yet.

**Comment by monlovesmango** [comment]
what all interactions would you want to mirror for? astral already auto mirrors when you reply/quote/repost an event.

**Comment by Giszmo** [comment]
Oh! Does it? Then I don't want to further waste your time with the issue.
