### ISSUE TITLE
Direct message throws error "could not publish dm event: Error: can't serialize event with wrong or missing properties"

### ISSUE THREAD

**Issue by 2minutebtc** [monlovesmango/astral#101]
"could not publish dm event: Error: can't serialize event with wrong or missing properties" is shown as I try to send a DM in Nostr. It used to work. Has this been seen before?

**Comment by monlovesmango** [comment]
hmm i haven't seen it. are you using the browser extension to sign? or is your private key entered?

**Comment by 2minutebtc** [comment]
the key is entered

**Comment by monlovesmango** [comment]
I am so sorry about that! it is fixed now. you may need to refresh astral. 

thank you for reporting this issue!
