### ISSUE TITLE
Lighting Address or LUD-06 identifier

### ISSUE THREAD

**Issue by dennj75** [monlovesmango/astral#103]
From nostr directory in twitter they told me to write here to try to solve my problem.
In Astral --> Setting I don't have anymore Lighting Address or LUD-06 identifier (Without it, it wouldn't make sense to have an open profile)
The problem born when I requested NIP-05 from Nostr.red | NIP-05 Our Handle Provider | By @BitcoinVoucherBot
A Nostr.red contact confirmed that my NIP-05 was active, I tried to configure it in setting several times but nothing happened.
At that point I was advised to try empty cache. I went into chrome history and cleared the cache.
When I tried to configure NIP-05 again it was ok but there was no more Lighting Address or LUD-06 identifier. Can you recover it?
![Astral_Setting](https://user-images.githubusercontent.com/57301944/214152942-9fbbcb85-1702-406c-ae5a-01604de0ddb2.png)

API info
Wallet ID: 93af26f44d7d43a2ae414e976591feae
Admin key: 23a28bf71e484e10887574eb0450fabd
Invoice/read key: f74ac222ad4a47aaac34c2fc4458d341

username:Dennj75
dennj75@nostr.red

public key of my profile
npub1lejpu7ms5j6y7srv32ndxw4m9j5vp7tgdjpsxw32h3r2y7zpqtdsdumyk0
convert:
fe641e7b70a4b44f406c8aa6d33abb2ca8c0f9686c83033a2abc46a2784102db
If you also need the private key, I can provide it.
I hope you will be able to help me, I would like to continue this adventure and with my original twitter profile.
Available to provide any other possible information

**Comment by monlovesmango** [comment]
hey there, i think you need to enable the LNURLp extension in lnbits and then follow this video: https://www.youtube.com/watch?v=WZpK4xfGcuY
or on github:
https://github.com/lnbits/lnbits/tree/quart/lnbits/extensions/lnurlp

then you can create an lnurl that can be entered on your profile.

**Comment by dennj75** [comment]
Found! A thousand thanks!
Excuse me but I'm new to this world... and unfortunately I didn't get there on my own.

**Comment by monlovesmango** [comment]
were all trying to figure out this new world together!

am I good to close out this issue?

**Comment by dennj75** [comment]
Absolutely yes!
A thousand thanks!
