### ISSUE TITLE
Posts don't show in profile pages

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#104]
Going to any profile page I see no posts of the user. I can see their follows and followers though.

Firefox, astral.ninja

**Comment by monlovesmango** [comment]
can you give me a random profile to try? I'm seeing posts pull up.

**Comment by Giszmo** [comment]
I cleared cache and it happens with all profiles with no error in the console.

[My profile](https://astral.ninja/npub1gm7tuvr9atc6u7q3gevjfeyfyvmrlul4y67k7u7hcxztz67ceexs078rf6) is as good as any other.

**Comment by monlovesmango** [comment]
this link worked for me in chrome but not in firefox. so firefox is broken with last update, which is weird bc I barely touched anything. i just reverted to the last version and firefox is working now. you will need to open astral and wati for new (last) version to download and then refresh (if you watch the console it will tell you when content has finished downloading)

**Comment by Giszmo** [comment]
yes. it works again. thanks.

**Comment by dmp1ce** [comment]
How do you know what version of Astral is being loaded on astral.ninja? I am still having issues with astral.ninja not loading the profile posts and follow feed. Does astral wait for all of the relays before showing posts? I am also using Firefox.

**Comment by monlovesmango** [comment]
hmm whats your npub? I can try to login as you and troubleshoot.

**Comment by Giszmo** [comment]
Yeah, it's still flaky. Having very unstable results with astral lately, including the above issue.
