### ISSUE TITLE
"Failed to verify NIP05 identifier on server" error

### ISSUE THREAD

**Issue by snarfed** [monlovesmango/astral#105]
Hi! First off, thank you for building and running astral. It's great!

I'm having trouble getting it to accept my NIP05 id. When I enter `_@snarfed.org` in the _NIP-05 identifier_ field on https://astral.ninja/settings and click _Save_, it says _Failed to verify NIP05 identifier on server._ I think I've set it up right though, based on https://github.com/nostr-protocol/nips/blob/master/05.md :

* `curl -v 'https://snarfed.org/.well-known/nostr.json?name=_'` returns HTTP 200 with the response below, `Content-Type: application/json`, and `Access-Control-Allow-Origin: *`:
    ```json
    {
      "names": {
        "_": "a01069041cd37e1c14159e0e5b2854e80420cc44299a446d2290b9cac0e234b3"
      }
    }
    ```
* The CORS preflight request `curl -v -X OPTIONS 'https://snarfed.org/.well-known/nostr.json?name=_'` returns HTTP 200 with `Access-Control-Allow-Origin: *`
* The NIP05 tester on https://astral.ninja/devTools seems to find it ok, I get this when I enter `_@snarfed.org`:
    ```json
    {
      "pubkey": "a01069041cd37e1c14159e0e5b2854e80420cc44299a446d2290b9cac0e234b3",
      "relays": []
    }
    ```

**Comment by monlovesmango** [comment]
hey there! so... it looks like a01069041cd37e1c14159e0e5b2854e80420cc44299a446d2290b9cac0e234b3 is your private key. for nip05 you need to list the public key, so for you it would be cfcc2bc32c92ec33e827ddc28b41dc2b40727ed44cee71a193e2d6b3523f6c03.

good news is when I tested logging in using a01069041cd37e1c14159e0e5b2854e80420cc44299a446d2290b9cac0e234b3 as the pubkey the nip05 did save correctly. so you should easily be able get your nip05 sorted out once you update it with the appropriate key.

bad news is that your private key is now compromised and you should discard this nostr key pair and start over with a new one. with your new key pair, make sure to use the npub key, converted into hex format for the nip05 json.

feel free to let me know if you have additional questions or issues

**Comment by snarfed** [comment]
Wow, that's embarrassing, and confusing. Sorry for this. I guess I thought astral's key generation gave me `a0106...` as the hex version of my NIP-19 public key `npub...`. So `a0106...` is the hex version of my NIP-19 private key `nsec...` instead? Funny, OK. I'll delete that account and keypair and generate a new one. Apologies again!

**Comment by monlovesmango** [comment]
correct. when i put your npub through astral's key converter it spit out 'cfcc2bc32c92ec33e827ddc28b41dc2b40727ed44cee71a193e2d6b3523f6c03'

no apologies needed! glad we could get it sorted!
