### ISSUE TITLE
Re-"tweet" is broken or I don't get how it works

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#11]
I opened event/a893213dc51c0a03719bb4d66d0eb11efe7f7b713aca0d42621c0239c5ea3ee6 from the global feed and found three buttons, none of which is featuring a tooltip. Clicking the double-arrows I get this:

![Screenshot from 2022-05-30 21-44-38](https://user-images.githubusercontent.com/96378/171076595-478a745a-b55d-4b9e-b79e-b43e93d3c46d.png)

Scrolling to the right only affects the scrollbar itself.

**Comment by Semisol** [comment]
That's a feature for publishing events of your follows in other relays to help it reach more people. If you don't follow the person, it'll be blank.

**Comment by Giszmo** [comment]
* A tooltip would be helpful then
* A special message explaining why it's blank (I still don't understand) would be helpful

**Comment by monlovesmango** [comment]
agree tooltip is needed.

for now i'm going to leave this be and let it look like a bug, I am hoping to be able to make this consistent with db updates

reason it is inconsistent is we only have the seen_on relay data for events that are fetched from the db. any event fetched directly from the relays will not have the relay data. (if you notice, none of the profile events have relay data available bc they are fetched directly from the relays)

**Comment by monlovesmango** [comment]
tooltip has been added.

repost and quote buttons are shown on the post now too to avoid confusion.
