### ISSUE TITLE
Need astral support for reply enhancement

### ISSUE THREAD

**Issue by arthurfranca** [monlovesmango/astral#112]
@monlovesmango please can you check out [this nostr issues](https://github.com/nostr-protocol/nips/issues/267) regarding thread enhancement?

It needs main client authors, like you, commit to supporting it for fiatjaf to consider a PR. At the end of the discussion, you can sse it would only need small tag addition when creating new reply events, totally backwards compatible. Your client would have to change nothing more than that.

**Comment by monlovesmango** [comment]
when you say that it would only need a small tag addition, that is assuming astral has already found all the relevant ancestors. it also doesn't factor in the logic needed to construct threads, which is supposed to be the whole reason you are creating this pr from my understanding. 

as is I am not a fan of this proposal, however I left my feed back in the issue and we can continue the discussion there.
