### ISSUE TITLE
Avoid avatars overlapping with text

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#12]
Especially the label is hard to read - with my avatar not even being label-colored which would make it worse:

![Screenshot from 2022-05-31 13-49-06](https://user-images.githubusercontent.com/96378/171252288-8db06d82-4f77-4e2a-85e1-37de49c01333.png)

Why not do it more like Twitter:

![Screenshot from 2022-05-31 13-51-56](https://user-images.githubusercontent.com/96378/171252796-c0088dab-54b4-456a-b3a3-183cc7fcdfa5.png)

Minimal changes:

![Screenshot from 2022-05-31 13-52-11](https://user-images.githubusercontent.com/96378/171252805-14a841e7-ddbc-41ee-a183-ec35e03aeb35.png)

**Comment by monlovesmango** [comment]
ok so I actually spent a lot of time debating how I wanted to do this. agree the text overlapping the avatar is not ideal. but I really hated wasting precious width just for a small profile picture on small screens (like 300px). despite astral being browser only I still really want it to be usable for smaller screens. and when you send a longer message on a smaller screen the wasted width space really bothered me.

ultimately I would rather get rid of the pic entirely than preserve width for it. can you think of another layout that might work better? do you think making the pic lighter would help?

also, I kinda like how it is right now, even if it is harder to see the words on top of the pic. I figure its text that the user typed themself, so they should know what it says.

**Comment by monlovesmango** [comment]
I still like the overlapping text look better for all screens so I will not be merging this pr. also as general practice I only want screen specific configurations when its for a functional purpose. 

I understand you don't agree with some of my UI choices, but at the end of the day I am creating astral based on my own UI preferences. if you feel strongly that this decision is wrong I would encourage you to fork astral and take it in your own direction. my guess is that there may be other users who are also bothered by the overlapping layout I went with and would appreciate a more defined layout with astral's functionality. the more clients on nostr tailored to different user preferences the better imo.

**Comment by Giszmo** [comment]
> the more clients on nostr tailored to different user preferences the better imo.

I strongly disagree on this line. If 1001 devs geek out each on their own client because they can't agree on basic stuff, no normie will ever use any of those clients in any significant way. The client that can unite open source brain power will make all others obsolete.

That said, I'm still searching my spot in nostr and will probably stick to reporting issues for astral as I started work on my own Android client. Close this issue if you think it's not a bug.

**Comment by monlovesmango** [comment]
I have made the icon in the post entry text box more transparent so that it doesn't interfere with the text as much
