### ISSUE TITLE
Wild things happen when hitting enter while writing a reply

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#15]
* Go to "follows" feed
* click on the reply icon of the first event
* type something
* type enter

Expected: Nothing spectacular happens. Just a newline appears in the textarea.

Actual: The view updates to the event one is replying to and the reply is gone.

**Comment by monlovesmango** [comment]
oh wow, thanks for finding! will fix

**Comment by Giszmo** [comment]
If I had to choose, this would be the first thing to fix ;)

**Comment by monlovesmango** [comment]
:) working on this now. should be fixed in the next few days.

**Comment by monlovesmango** [comment]
few days took longer than I thought (haha as always...). this is now fixed.
