### ISSUE TITLE
web+nostr URI scheme is broken

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#16]
While branle can handle web+nostr links such as

```
web+nostr:event:2757368bc06504ad23baabf358d91c7d5e55845b3432a6ba4e1e546ac367621c
```
astral cannot.

src/pages/Profile.vue:111 contains the relevant code for above link but I get " 404 Oops. Nothing here..." instead.

**Comment by monlovesmango** [comment]
this should be easy to restore, even if its just experimental still. will fix.

**Comment by monlovesmango** [comment]
hey looks like fiatjaf removed the web+nostr stuff from branle so its not gonna be used. given that i'm not inclined to add this back to astral. closing.
