### ISSUE TITLE
event info is broken

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#19]
I think the "i" next to every event was to show the raw event. this button does not work for me.

**Comment by Giszmo** [comment]
Turns out the button is flaky. Sometimes it works, sometimes it doesn't. One has to hover over it for a second until it changes color to get a reliable result.

**Comment by monlovesmango** [comment]
I'm not sure there's anything I can do about this minor lag unless you have any ideas? if not i'm going to close this issue.

**Comment by Giszmo** [comment]
There is also an inconsistency: In DMs, the right-button menu always works instantly I think but it's just that: inconsistent. Why do things differently there?

**Comment by Giszmo** [comment]
Regarding the "lag": Here it's not just a lag. Sometimes the button reacts turning bright and goes dark again without doing anything. It's really flaky.

**Comment by monlovesmango** [comment]
hey this is fixed now.
