### ISSUE TITLE
Detect and handle disconnects

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#21]
The app turns unusable when going through a PC suspension (and probably also when internet is gone for some time?). Handle those events, detecting websocket disconnects for example and restore state when the tab gets focus or show a "refresh" button to the user that lets him restore the state without closing or reloading the tab.

**Comment by monlovesmango** [comment]
I added something to close all db listeners on reload/leaving page. can you let me know if behavior is more consistent now? still get some listener errors when I click around too much, but at least now refreshing can help.

didn't want to put too much effort into this as I am going to be trying to get rid of pouchdb next

**Comment by Giszmo** [comment]
Refreshing is not easy neither. Will try closing and re-opening the tab next.

**Comment by monlovesmango** [comment]
this is fixed now, closing.
