### ISSUE TITLE
load events newest to oldest, not oldest to newest

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#22]
shift-reload currently takes several minutes here, starting with January events to get to recent events.

**Comment by monlovesmango** [comment]
was this in regards to the profile page? if so this is fixed now.

**Comment by Giszmo** [comment]
Well, sort of. Now I see something like "load one more day" which I can click and wait a few seconds for nothing to happen. If my latest events are 25 days old, do I have to click and wait 25 times?

**Comment by Giszmo** [comment]
That issue from the prior comment might have been before refreshing the DB. It now works smoothly.
