### ISSUE TITLE
Don't count markdown and links against the message size limit

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#23]
I'm not sure where the comment size limit came from in Astral but other clients allow much longer messages.

I think there should be some Twitter-like short-ish limit but links should not count against that limit or at least not in full.

Maybe the client should count the link title in full (or generally apply the limit to the markdown-applied text) and use a much more generous limit for the serialized event's size.

**Comment by monlovesmango** [comment]
for now I'm just keeping the limit to keep the twitter-like feel.

now when links are added they will just be attached to the post and won't be counted in the char limit. only text will be counted in character limit. there is also a section in the post entry to add a link with a name.
