### ISSUE TITLE
I guess astral fails to interpret something here ...

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#24]
`event/407fa3bfa42b38f1d0c1707440c9794ab81da27622393ca1b617d2adcc724b59` looks weird here:

![Screenshot from 2022-06-09 21-42-22](https://user-images.githubusercontent.com/96378/172973557-7a7a454d-2238-4a17-926c-48531f106441.png)

Due to #19 it's a bit cumbersome to investigate.

**Comment by monlovesmango** [comment]
this is fixed now, though it still is a bit slow it does populate. closing.

previously if an event wasn't received in time I cancelled the request which lead to empty quote events being listed.
