### ISSUE TITLE
Duplicate webservice requests are being sent

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#26]
Looking at the Firefox dev console Network tab, inspecting what Astral does with nostr.rocks I noticed many duplicate requests:

![Screenshot from 2022-06-13 18-25-22](https://user-images.githubusercontent.com/96378/173457705-a88b7230-3c93-4109-b0b7-35475f0beb40.png)

**Comment by monlovesmango** [comment]
completely revamped the way I request from the relays and this is fixed! closing.
