### ISSUE TITLE
Prevent removing all functioning relays

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#28]
Astral gets the list of preferred relays using its default list of relays.

If that list contains only defunct relays, it's hard to recover as I have to manually add all default relays to get my fixed list to all default relays so that at the next start of using astral I don't fall back to my defunct relays.

**Comment by Giszmo** [comment]
So I'm still not sure what exactly is happening. I checked all default relays and my own localhost relay and none of them gives me back the bad relay or a list of one at all. They are now all well seeded with a long list of relays (except for the fiatjaf relays that don't reply).

My query is `["REQ","name",{"limit":7,"authors":["46fcbe3065eaf1ae7811465924e48923363ff3f526bd6f73d7c184b16bd8ce4d"],"kinds":[3]}]`.

Ok, I found the culprit. The bad relay was sitting in the DB. After hitting "delete local data" I now don't get the bad relay anymore.

**Comment by Giszmo** [comment]
Actually ... I think the best solution is to not remove relays at all. Just make them noRead/noWrite. To not clutter the UI, those can be as suggestions in the dropdown and for extra fancyness, removal from dropdown could actually delete them from the list.

**Comment by monlovesmango** [comment]
i decided to just leave them displayed (so users don't get confused by disappearing relays) but move them to the bottom of the list and change the share button to a remove button. this way its still a two step process to remove the relay completely (first turn off read/write, second remove the relay) and its easy to understand without hiding anything.

**Comment by Giszmo** [comment]
Turning off read and write should also avoid a channel to be opened.

The save button does not show any feedback on success or need to be pressed. Please make it such that

* when I edit relays, the disabled save button gets enabled
* when I hit the save button, show a spinner
* when saved, make save button disabled again

**Comment by Giszmo** [comment]
I think, Astral bootstraps from some default relays, so if removing all of those doesn't get stored with those, I always load what was last stored to any of those. Can't Astral bootstrap from the DB instead? Load the used relays from DB and only fallback to default relays if DB not available? And maybe unsubscribing from a relay should still be persisted at that relay?

**Comment by monlovesmango** [comment]
this is already the behavior I believe. loads the default list of hard coded relays until the db responds with the most recent relay list. its not querying the default relays for the relay list.

for the save button, it already should get disabled after saving but saving is kinda slow/erratic. will try to make this more consistent

**Comment by Giszmo** [comment]
Ok, the default relays flashing at reload is a bit irritating but good to know they are only flashing, not being used.
