### ISSUE TITLE
Unfollowing does not remove notes from follows feed

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#3]
Running Astral on what I think is effectively current master HEAD, I see messages of unfollowed accounts in my "follows" feed.

This problem persists for days, with many reloads and tab close and re-opens.

I unfollowed jb as can be seen on the "following" list, yet I see many of their notes.

![Screenshot from 2022-05-29 12-26-07](https://user-images.githubusercontent.com/96378/170880584-2cda0103-e602-45ab-acba-1e37cdc483ae.png)

While some "in reply" ones were in reply to my notes, so those should probably stick around, the screenshot also contains one that is not "in reply".

**Comment by monlovesmango** [comment]
yeah currently the only way to remove is to remove all data and then resync which is a huge pain. I am working on db stuff now so going to fix this at the same time (don't really want to do a short term fix for this)

**Comment by monlovesmango** [comment]
this is fixed now, closing.
