### ISSUE TITLE
Feature: Show followers

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#30]
Querying followers is easy enough (`{"#p":[pubkey],kinds:[3]}`). Why not add it to the clients?

At least in the own follows list it would be nice to know who followed back.

And on events and chat it should be visible if the author is following me.

(More importantly, show if it's the monlovesmango I am following or an imposter on events and chat).

**Comment by monlovesmango** [comment]
i like this. I think it only makes sense to show if you are following someone on posts and chats (not if they are your follower since this is easy to fake), would you agree?

**Comment by Giszmo** [comment]
In my client I plan to support followers among the n-th degree of follows, ignoring blocked accounts in the logic. So if I follow Alice and Alice follows spam bot researcher Bob who follows 3000 bots that all follow me, I won't see those followers if I block Bob. So Followers would also be displayed with the link via which I follow them.

The idea is that if I see SpamBot3 among my followers, I might block it but when I then see SpamBot[4-12], I would click on their profiles and see: "Your link: You -> Alice -> Bob -> SpamBot4" and could just block or mute Bob.

**Comment by monlovesmango** [comment]
followers have been added. 

I am not sure I want to add an indicator for people who follow you (since you can't control that) but still want to add indicator for posts that are from your follows (so its hard to impersonate the people you have chosen to follow)

**Comment by Giszmo** [comment]
Great you show the followers now.

I agree on the point of you not controlling who follows you but ... for those you do follow, it's interesting to see if they also follow you and in the list of followers it would also be nice to see the followers you follow first and the others maybe only if you hit a button. In Nostroid I plan to show followers that way, with further distinction for the "others". The list would be clearly divided:

* followers from your follows
* followers from your follows' follows
* followers from your follows' follows' follows

to probably stop right there or have a button to go deeper. Followers that are not connected at all is a failure of Twitter to consider. Yes, that makes it an invite-only club but without any limitations on how many you can invite to the club I think that's fine.

**Comment by monlovesmango** [comment]
i may add something like this in the future, but at this point I think it is overkill.

for now I have added an eye icon next to any user whom you follow, just so you can easily identify posts from your follows.

**Comment by Giszmo** [comment]
As the title of this issue was resolved, I would have closed this one and kept #41 open.

**Comment by monlovesmango** [comment]
as you wish :)

closing
