### ISSUE TITLE
Poor error handling on db failure

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#32]
Apparently Astral doesn't work in "private" browser windows but doesn't tell the user to not try.

![Screenshot from 2022-07-13 22-47-41](https://user-images.githubusercontent.com/96378/178887535-eac09edc-4bca-467a-9813-c69a6fea5b0a.png)

**Comment by monlovesmango** [comment]
hmm this works in my private browser window. what browser are you using?

**Comment by Giszmo** [comment]
FF 96.0.3
Chromium 103.0.5060.53

Debian

**Comment by monlovesmango** [comment]
note for me: 
https://jasonsavard.com/forum/discussion/7321/firefox-private-browsing

**Comment by monlovesmango** [comment]
ok I trashed the indexeddb and absurd-sql so this should no longer be an issue.

**Comment by Giszmo** [comment]
you trashed both IDB and ASQL or only IDB+ASQL? What are you using instead?

**Comment by monlovesmango** [comment]
i'm just using sql.js. so kept all the sql stuff but not using indexeddb for it (just browser temp storage)
