### ISSUE TITLE
The new version freezes the tab beyond reloads

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#37]
I now am looking at a "This tab is slowing down FF" for many minutes at a time, with nothing working in Astral and hitting F5 does not help. It only returns to freeze.

**Comment by Giszmo** [comment]
turns out node v18 does compile but the result is causing issues. With node v16 above issue is not reproducible.

**Comment by monlovesmango** [comment]
this should be fixed. if not let me know and I can reopen.
