### ISSUE TITLE
Messages counter increments without showing the messages (quickly?)

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#4]
Now as I opened my nostr tab, it showed me one new message and selecting "messages" it was one new message on chat with 8c0da4 but I saw no new message there. Only later when going back to that chat that new message from 3h ago did appear.

**Comment by monlovesmango** [comment]
this is also a db thing that will hopefully improve with db updates

**Comment by monlovesmango** [comment]
with the latest commit

**Comment by monlovesmango** [comment]
this should be fixed now
