### ISSUE TITLE
I think there is a bug with nip05

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#44]
https://astral.ninja/6b0d4c8d9dc59e110d380b0429a02891f1341a0fa2ba1b1cf83a3db4d47e3964 shows the name "dergigi" but no information about nip5.

https://dergigi.com/.well-known/nostr.json:

```
{
  "names": {
    "_": "6b0d4c8d9dc59e110d380b0429a02891f1341a0fa2ba1b1cf83a3db4d47e3964"
  }
}
```
looks good.

The relevant event:

```
{
  "id": "45f21a870ad194b914d93c553e59c1b0ab242a76b0d66b425323ef4baba212ff",
  "pubkey": "6b0d4c8d9dc59e110d380b0429a02891f1341a0fa2ba1b1cf83a3db4d47e3964",
  "created_at": 1663236946,
  "kind": 0,
  "tags": [],
  "content": "{\"name\":\"dergigi\",\"picture\":\"https://dergigi.com/assets/images/avatar-laser.jpg\",\"about\":\"Writing words and code for Bitcoin. dergigi.com\",\"nip05\":\"dergigi.com\",\"lud06\":\"LNURL1DP68GURN8GHJ7MR9VAJKUEPWD3HXY6T5WVHXXMMD9AKXUATJD3CZ7CTSDYHHVVF0D3H82UNV9UENXVPSXRPGRS\"}",
  "sig": "c10e66983593ceedcd8a37b76ff0726b78dc425da394935388e7636b9b1d3b4010886a922bd5c79d16140d26d99fb7dcdfbe4844b9d8b2835dd5bbe8916d5232",
  "degree": 0
}
```

also looks good.

The keys match.

What am I missing?

If Astral thinks the nip05 is wrong, it should probably also state that and why. It might be a huge red flag for somebody to use a "fake" nip05 entry.

**Comment by monlovesmango** [comment]
he needs to enter it as _@dergigi.com in order for NIP05 to be validated (since the name key is '_'). 

I don't really see this as a huge red flag, bc no one will see them as a verified user anyway and won't give them additional trust. plus right now this will just cause unnecessary confusion as most just mess up the NIP05 setup.

closing.
