### ISSUE TITLE
Feature: When checking the "raw" DM, show the decrypted "raw" content, too.

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#45]
Astral interprets the decrypted content, replacing profile hrefs with profile name etc., so the user might want to see what the other actually sent.

I was surprised to find
`<a href=/$pubkey>$someMessage</a>` gets replaced with something not containing `$someMessage` at all. Maybe it could be added back as title?

**Comment by monlovesmango** [comment]
I kinda want to keep the metadata pure to what is exposed over nostr network.

anywhere that a person or event is tagged in the text will just be the confusing #[<tagNo>] notation so I don't see much value in building UI functionality to expose that. you can always query it with dev tools if you want.

not sure what you are referring to for the `<a href=/$pubkey>$someMessage</a>` piece, can you specify where you are seeing this?

**Comment by Giszmo** [comment]
Well, it's in a DM, so ...

unclebobmartin is testing stuff, so he sent me those:

![Screenshot from 2022-09-27 08-37-46](https://user-images.githubusercontent.com/96378/192515539-a8d2502b-dbb5-410d-ba5b-e5418b4b74ef.png)

```
{
  "id": "8f96583ba97a3de0bb71a42200a521444316b2b9224f95287ab43499bac974fb",
  "pubkey": "2ef93f01cd2493e04235a6b87b10d3c4a74e2a7eb7c3caf168268f6af73314b5",
  "created_at": 1663592545,
  "kind": 4,
  "tags": [
    [
      "client",
      "more-speech - 202209051410"
    ],
    [
      "p",
      "46fcbe3065eaf1ae7811465924e48923363ff3f526bd6f73d7c184b16bd8ce4d"
    ]
  ],
  "content": "CPy8Ls9Z3sVVz+5IINk23qN1D1K8J9ty3FcxVlfWaMyj6dOBEeqPPK4SZ+LPdk9a?iv=k8iNB6mf1uQP2vAjPbyhog==",
  "sig": "2d358556895360c5b35c23974455ff11c8bb582ec195f5646a40fa58c9db6c756cb2ba2986969436e2777fdb052ce207bd0e504ed55a2bae7f1cd89cce493554"
}
```

That `D @leo@nostr.info` turns out to be rendered from `D <a href="/46fcbe3065eaf1ae7811465924e48923363ff3f526bd6f73d7c184b16bd8ce4d">Profile 46fcbe3065eaf1ae7811465924e48923363ff3f526bd6f73d7c184b16bd8ce4d</a>`. I'm not 100% sure about the href's content but whatever it is, astral understands it as a pubkey and replaces the `Profile 46fcbe3065eaf1ae7811465924e48923363ff3f526bd6f73d7c184b16bd8ce4d` with `@leo@nostr.info`. In Nostroid I want to do something similar, primarily to show if the profile is mine, followed or unconnected but I don't know neither what to do with the a-tag's body.

**Comment by Giszmo** [comment]
Strike that other comment.

unclebobmartin had me confused by using a mention in a DM which had me thinking about privacy of those mentions. You don't want tag based mentions as those are not encrypted but when checking the "raw" content, I saw an a-href. I didn't check the actual raw content though, but the already interpreted content from my Nostroid.

As he was mentioning the recipient of the DM, there was no leak but no idea where he was going with this and if his client would have added more tags had he mentioned others.

**Comment by Giszmo** [comment]
That said, with Nostroid I want private mentions in both DMs and Notes. In Notes they would still  be discoverable with full-text search of course but in DMs it would prevent the leak. I would opt for `#[<pubkey>]` as it's close to the tag based way and thus easy to parse.

**Comment by monlovesmango** [comment]
but other clients prob will not parse #[<pubkey>] in dms.

was there anything else to address with this issue?

**Comment by Giszmo** [comment]
> but other clients prob will not parse #[] in dms.

Same problem with every other new feature, too. This would require a nip but I find it easy to implement if done as mentioned above.

> was there anything else to address with this issue?

no
