### ISSUE TITLE
Fix layout shifts on new events being recieved

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#50]
New events being received pushes the feed down and with images  or when unclebobmartin posts, by a lot.
As sorting can also change when a new reply for an older thread is received, the stuff the user was reading might have moved up or down.
This can be quite disorienting

Maybe slowly smooth in a one-line event counter like Twitter has it: "Show 25 Events".

Due to the re-sorting I don't see any good alternatives to this.

**Comment by monlovesmango** [comment]
this has been implemented. closing.
