### ISSUE TITLE
Make Astral multi-account capable

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#52]
Currently, to use multiple accounts I either have to use multiple browsers, browser sessions, Astral instances or wipe the data to sync from zero when switching accounts.

As in many if not most cases, many events are relevant to all one's accounts it makes sense to have the client be multi account capable.

**Comment by monlovesmango** [comment]
created a logout option. don't think I want to support multi account use explicitly, so this should be good enough. closing.
