### ISSUE TITLE
Message size counter gets confused if the user clicks somewhere into the curren message

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#54]
1. Hit reply on any event
2. Author a way too long message
3. Send button gets disabled
4. Click for example on the first line of your message
5. Send button gets enabled
6. Sending actually works

[Example Event 435c44c5b5dd8abceefe5f4ac176165618732178f4864d822979153a3fe9ad7f](https://chat.nostr.info/event/435c44c5b5dd8abceefe5f4ac176165618732178f4864d822979153a3fe9ad7f/)

**Comment by monlovesmango** [comment]
this should be fixed now. closing.
