### ISSUE TITLE
Thread view broken

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#55]
I made a [post](https://astral.ninja/event/7f6a13d63fd0e3b5df5ce6f6479c4ab5f2236be761416003078bc0e905f52425) and astral doesn't show the replies. I can open for example [this reply](https://astral.ninja/event/aa5ba0f37af0ceb21c08454324fd7caa310781a5a29decfeb205acbb91439baa) just fine but it doesn't show on the former link.

**Comment by monlovesmango** [comment]
hmm thats very weird. I am seeing the replies when i go to the 'post' link. maybe the replies hadn't been loaded to the db yet?

![image](https://user-images.githubusercontent.com/96307647/198846725-c8d29893-5273-4b89-a85c-92fb7c236477.png)

**Comment by Giszmo** [comment]
I also thought it might not be in the db yet but as I could load the one reply just fine I would expect that's indicative of the event being in the db but still, loading again the parent event the reply was missing. Now it loads fine.

**Comment by monlovesmango** [comment]
have you seen this happen again? can I close?

**Comment by Giszmo** [comment]
I haven't noticed it again. Closing.
