### ISSUE TITLE
Feature Request: Improved CSS 

### ISSUE THREAD

**Issue by improvethings** [monlovesmango/astral#58]
Maybe just adopt a standard tailwind css template to improve the aesthetic?

**Comment by monlovesmango** [comment]
hey. i know the ui is not great but rather have the flexibility of not using a template. were there specific aspects that you think should be improved?

**Comment by improvethings** [comment]
I just noticed the colour preferences, thanks for that! 

- The ability to slide and save the boundary lines would be great
- Add a colour preference for background as well
- Ability to change font from a pulldown

**Comment by monlovesmango** [comment]
these are great suggestions thank you! I don't think I will implement the slide bc this introduces a lot of complexity in maintaining layouts for different screen sizes, but I will definitely put the other 2 on the todo list.

**Comment by monlovesmango** [comment]
@improvethings background and font customization is now in astral.

**Comment by sshmatrix** [comment]
> @improvethings background and font customization is now in astral.

Hi, can you please point where the customisation exists? I have been trying to change default font but it seems like all standard ways of changing default font in Quasar are somehow being overriden.

**Comment by monlovesmango** [comment]
hey there, font customization lives in astral's settings page. is that setting not working for you? its right below the color settings.
