### ISSUE TITLE
Promote mnemonic as the primary security rather than a single private key

### ISSUE THREAD

**Issue by synace** [monlovesmango/astral#63]
NIP06 mnemonic is already supported by mutations.js via the existing frontend key input box. In fact, it is the mechanism by which a new private key is already generated.

However, there's no way for the user to see the mnemonic (it's ephemeral within the function call and lost once the private key is returned), and there's no clear indication that mnemonic is supported by the input box even though it is.

1. Indicate that mnemonic is supported in the "key" input
2. Change "generate" to show the mnemonic (and an advanced button to see the private key) 

Preferring and promoting the use of the mnemonic will afford all of the already established benefits seen by other applications of BIP39.

**Comment by monlovesmango** [comment]
this is a great suggestion! definitely think its worth supporting this. and then you can easily turn bitcoin addresses into nostr ids (not that I suggest doing this... but still cool as makes it easy to sign messages to prove ownership). will need to change to npub/nsec format in near future and will account for this as well.

thanks!

**Comment by vishalxl** [comment]
There are already attacks in wild where some clients/apps are asking for bitcoin seed phrase to log in to nostr. See [here](https://twitter.com/BTCMinstrel/status/1605948366646521857). At this point, and till indefinitely till we understand the situation or problem, bitcoin word itself should be kept away from nostr, and ideally no nostr log in should be derived from bitcoin seeds.

**Comment by monlovesmango** [comment]
got it thanks for chiming in @vishalxl

**Comment by monlovesmango** [comment]
@synace i'm going to close this issue since I don't think we want to recommend bitcoin seed phrase type sign on right now. agree its a really nice idea though.
