### ISSUE TITLE
Some of the DMs are rendered with three questionmarks

### ISSUE THREAD

**Issue by 0xtrr** [monlovesmango/astral#64]
_Creating a bug for this even though I know you know about it already @monlovesmango._

## Description
Sometimes some of the DM events are rendered with three questionmarks instead of the actual message. If this happens, we can just reload the page and the messages should be decrypted and rendered as expected.

Here is a screenshot of our conversation about this bug:
![screenshot](https://user-images.githubusercontent.com/86188777/208471587-41a98cdd-9363-4112-83c9-a044b8d2ca02.png)

**Comment by monlovesmango** [comment]
hey @0xtrr thank you for logging this issue. this should be fixed now, can you confirm?

**Comment by 0xtrr** [comment]
tbh, I haven't experienced this after I created the issue @monlovesmango so I guess it's fixed?

**Comment by monlovesmango** [comment]
it wasn't fixed but it only occurs in certain scenarios so its easy to not experience it. i'll close for now, feel free to reopen if you experience this again.
