### ISSUE TITLE
Error message blocks bottom navigation UI

### ISSUE THREAD

**Issue by pseudozach** [monlovesmango/astral#70]
Thanks for making my favorite nostr client!

Here's my issue:
When using as a mobile app on android, bunch of error messages pop up on the bottom of the screen and it blocks the navigation UI so I can't click away.

Plus errors are inactionable and I couldn't find a easy way to close them or swipe them away.

![Screenshot_20221221-234108](https://user-images.githubusercontent.com/3731591/209082764-2442bcd3-c0a2-450f-b90b-5b3aee29f2d2.png)

**Comment by leesalminen** [comment]
Submitted a PR to resolve this issue by presenting users with a "Close" button in error messages.

**Comment by vishalxl** [comment]
Same pic for desktop, just for reference, on chrome/windows. 
<img width="1280" alt="2022-12-23 (7)" src="https://user-images.githubusercontent.com/64505169/209289253-286517d8-087b-42a2-9316-5e370b612b1d.png">

**Comment by monlovesmango** [comment]
done. notifications for relays have been removed for now and close button has been added to all other notifications.

will be adding a relay status component to display these notifications.
