### ISSUE TITLE
Reply on a mention is referring to the wrong event.

### ISSUE THREAD

**Issue by mutatrum** [monlovesmango/astral#72]
I got mentioned by someone, and the comment button looked like it was in the wrong box:

![image](https://user-images.githubusercontent.com/56344102/209245119-9068b27d-b4d3-4364-a515-a4f2e7413be0.png)

When trying to reply, it replied to my own event, instead of the outside event.

Outside event id `a065bb1cc8a1b308e5b9bdd472722258dc7f55b5d6a398b43b2c3d7826858f2d`

**Comment by pfoytik** [comment]
did you happen to just hit the wrong reply button? Looks like you might have cut it off in your screen shot, I see a reply for both original post and a reply button for the quoted post see below:

![image](https://user-images.githubusercontent.com/30268344/209253682-fb1bedea-333b-4ae6-892a-2397d6c2e8a3.png)

The reply for shared post responded to the shared post not the original post.
![image](https://user-images.githubusercontent.com/30268344/209253745-e8111fa0-fca5-49d9-82ef-683cee38d526.png)

**Comment by monlovesmango** [comment]
no for reposts I removed the reply button to encourage people to engage with the original content. if you quote repost something replies are still allowed (since youre adding your own content). do you guys think that makes some sense or is that dumb?

**Comment by pfoytik** [comment]
ohhhhhh I see instead of the quote post. Yes I agree with you, if its a quote post then there is new content to discuss, if its just a repost all comments should be directed to the original post.
