### ISSUE TITLE
searchbox should not convert to lowercase

### ISSUE THREAD

**Issue by pseudozach** [monlovesmango/astral#73]
After typing or pasting `_PyBlock_@nostr.directory` into the searchbox and clicking search, the text is converted to lowercase which breaks nostr.directory API which is case-sensitive.

![image](https://user-images.githubusercontent.com/3731591/209276891-c3dd0864-dbf5-4b13-9fe0-81b64854583b.png)

>Request URL: https://nostr.directory/.well-known/nostr.json?name=_pyblock_
Request Method: GET
Status Code: 404

**Comment by monlovesmango** [comment]
why is nostr.directory api case sensitive? nip05 should not be. they are not operating per spec. https://github.com/nostr-protocol/nips/blob/master/05.md

**Comment by pseudozach** [comment]
Sorry about that, yes will need to fix that on my side.

**Comment by pseudozach** [comment]
fixed https://github.com/pseudozach/nostr.directory/commit/0f00369ac571fd9edba2fe36880da1cae55b0611
