### ISSUE TITLE
Losing follows on initial sync+follow

### ISSUE THREAD

**Issue by vilm3r** [monlovesmango/astral#76]
Steps to reproduce:
1. Have existing follows
2. Open astral on first time device/browser (or after clearing browser data/worker)
3. Add new follow before existing NIP-02 is received
4. Follows list is overwritten with single follow

**Comment by monlovesmango** [comment]
oof will fix thanks for reporting

**Comment by monlovesmango** [comment]
hey I have updated astral to warn you when you follow someone and a follow list hasn't been loaded. also astral should load your contacts much more promptly now. closing.

**Comment by vilm3r** [comment]
I was able to trigger the modal using the steps above. Thanks for the fix 👍
