### ISSUE TITLE
Clicking on links in profiles doesn't work

### ISSUE THREAD

**Issue by Giszmo** [monlovesmango/astral#8]
Stacker.news 076161ca22da5a2ab8c74465cbf08f79f3e7e8bb31f4dc211bd94319ebade03d has this profile description:

> Like Hacker News, but we pay you Bitcoin. https://stacker.news/

Clicking the correctly styled link does not open the link.

**Comment by monlovesmango** [comment]
thank you for finding this! fixed. closing.
