### ISSUE TITLE
Requesting input on NIP-23

### ISSUE THREAD

**Issue by dskvr** [monlovesmango/astral#84]
Hey there, NIP-23 is at a bit of a standstill. We need some input from client developers. The NIP has taken a turn as of a few days ago with some proposed simplifications. Would be extremely helpful if you provided your input. 

https://github.com/nostr-protocol/nips/pull/32#issuecomment-1367345226

Thanks!

**Comment by monlovesmango** [comment]
i like this NIP, left a comment saying so. was there anything else in particular you wanted me to speak to?

**Comment by dskvr** [comment]
Hey! Nope, the NIP went stale for a few months and was revived a while back. fiatjaf then expressed doubt and made alterations since you originally participated in the conversation. He hinted he wanted some client dev input so I reached out to a few people.  Since you previously participated I reached out.
